spring.application.name=dapp-2
server.address=0.0.0.0
server.port=8080

cardano.cli.path=/home/aiquant/.local/bin/cardano-cli
cardano.socket.path=/home/aiquant/git/cardano-node/preprod/db/node.socket
resource.path=/home/aiquant/cardano-tmp/
frontend.url=http://localhost:3000,http://16.171.145.142:3000,http://56.228.1.44:3000
