spring.application.name=dapp-2
server.port=8080

cardano.cli.path=/home/snehasish/.local/bin/cardano-cli
cardano.socket.path=/home/snehasish/git/cardano-node/preprod/db/node.socket
frontend.url=http://localhost:3000
